repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: pretty-format-json
        args: [--autofix]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        args: [--fix, --no-cache]
        language: system
        types: [python]
      - id: black
        name: black
        entry: black -l 100 .
        language: python
        language_version: python3.10
        types_or: [python]
      - id: mypy
        name: mypy
        entry: mypy --install-types --non-interactive .
        pass_filenames: false
        language: system
        types: [python]
